test

* Writing GNU Emacs Extensions

** Chap. 1

M-x apropos

** Chap. 2

Functions: other-window, move-to-window-line, file-smylink-p, message, remove-hook,
find-alternate-file, delete-file, write-file, read-buffer

Variables: buffer-file-name, prefix-numeric-value, current-prefix-arg

Hooks: post-command-hook, write-files-hooks, find-file-hooks, 

Advices: defadvice
Example: (defadvice switch-to-buffer (before name activate compile) ...)


** Chap. 3

Functions: defvar, set-window-start

Variables: last-command

Symbol properties: (put 'symbolname 'propertyname value), (get 'symbolname 'propertyname)

Markers: Like saved points but updated when the buffer is modified. set-marker


** Chap. 4

User options: (defvar varname value "* \\[command] docstring blabla")

Functions: (interactive "*") checks buffer is not read-only, save-excursion, save-restriction (narrowing),
save-match-data (search data), insert, match-beginning, replace-match, re-search-forward, regex-quote (escape a string),
make-local-hook, make-local-variable (if there is a global value for the other buffers), make-variable-buffer-local (separate
buffer-local in every buffer)

Regex: \< \> (beginning / end of world only), \bgnu\b (\b beginning or end of world), \= (empty string at current point)

Hooks: after-change-functions, local-write-file-hooks, 


